apiVersion: v1
kind: Service
metadata:
  name: musiccollection-backend
spec:
  type: NodePort
  selector:
    app: musiccollection-backend
  ports:
    - port: 4000
      targetPort: 4000
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: musiccollection-backend
spec:
  selector:
    matchLabels:
      app: musiccollection-backend
  replicas: 1
  template:
    metadata:
      labels:
        app: musiccollection-backend
    spec:
      containers:
        - name: musiccollection-backend
          image: ghcr.io/alexanderboldt/musiccollection:10.2.0-stage
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: musiccollection-postgres-secret
            - secretRef:
                name: musiccollection-minio-secret
            - secretRef:
                name: musiccollection-backend-secret
          ports:
            - containerPort: 4000
