quarkus:
  devservices:
    enabled: false
  datasource:
    db-kind: postgresql
    jdbc:
      url: ${POSTGRES_URL}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  flyway:
    enabled: true
    migrate-at-start: true
  oidc:
    auth-server-url: ${AUTH_SERVER_URL}
    client-id: ${AUTH_CLIENT_ID}
    credentials:
      secret: ${AUTH_CLIENT_SECRET}
    application-type: service
    roles:
      source: accesstoken
      role-claim-path: cognito:groups
    token:
      principal-claim: sub
  s3:
    aws:
      region: ${S3_REGION}

bucket:
  artist: ${BUCKET_ARTIST}
  album: ${BUCKET_ALBUM}
