apiVersion: v1
kind: Service
metadata:
  name: musiccollection-rustfs
spec:
  type: NodePort
  selector:
    app: musiccollection-rustfs
  ports:
    - name: api
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30020
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: musiccollection-rustfs
spec:
  selector:
    matchLabels:
      app: musiccollection-rustfs
  serviceName: musiccollection-rustfs
  replicas: 1
  template:
    metadata:
      labels:
        app: musiccollection-rustfs
    spec:
      containers:
        - name: musiccollection-rustfs
          image: rustfs/rustfs:latest
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: musiccollection-rustfs-secret
          ports:
            - name: api
              containerPort: 9000
            - name: console
              containerPort: 9001
          volumeMounts:
            - name: musiccollection-rustfs-storage
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: musiccollection-rustfs-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
