apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-keycloak
spec:
  selector:
    matchLabels:
      app: postgres-keycloak
  serviceName: postgres-keycloak
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
        - name: postgres-keycloak
          image: postgres:17.4
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef:
                name: postgres-keycloak-secret
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-keycloak-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-keycloak-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 1Gi
